// COPYRIGHT Dassault Systemes 2022
//===================================================================
//
// IdentityCard.h
// Supplies the list of prerequisite components for framework TRACommandAddinFW
//
//===================================================================
//
// Usage notes:
//   For every prereq framework FW, use the syntax:
//   AddPrereqComponent ("FW", Public);
//
//===================================================================
//
//  Jun 2022  Creation: Code generated by the CAA wizard  Dell
//===================================================================
// DO NOT EDIT :: THE CAA2 WIZARDS WILL ADD CODE HERE
AddPrereqComponent("System",Protected);
AddPrereqComponent("CATAssemblyInterfaces",Protected);
AddPrereqComponent("DialogEngine",Protected);
AddPrereqComponent("Mathematics",Protected);
AddPrereqComponent("Dialog",Protected);


AddPrereqComponent("ApplicationFrame",Protected);


AddPrereqComponent("MecModInterfaces",Protected);
AddPrereqComponent("ObjectSpecsModeler ",Protected);
AddPrereqComponent("ObjectModelerBase ",Protected);
AddPrereqComponent("KnowledgeInterfaces  ",Protected);
AddPrereqComponent("Visualization  ",Protected);
AddPrereqComponent("ProductStructure  ",Protected);
AddPrereqComponent("ObjectModelerNavigator  ",Protected);


 
// END WIZARD EDITION ZONE
